# Generated by Django 2.0.9 on 2018-10-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='criado_em',
            field=models.DateField(auto_now_add=True, verbose_name='data de criação'),
        ),
    ]
