# Generated by Django 2.0.9 on 2018-10-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20181021_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='modificado_em',
            field=models.DateField(auto_now=True, verbose_name='data de modificação'),
        ),
    ]
