# Generated by Django 2.0.9 on 2018-11-06 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_auto_20181106_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
