# Generated by Django 2.0.9 on 2018-11-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_pesquisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='produto',
            field=models.ManyToManyField(to='loja.Produto'),
        ),
    ]
