# Generated by Django 2.0.9 on 2018-11-09 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_pesquisa_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='criado_em',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='data de criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisa',
            name='preco',
            field=models.IntegerField(default=2.0),
            preserve_default=False,
        ),
    ]
